version: "3.9"
services:
  webpage_word_counter:
    image: node:slim
    working_dir: /usr/app
    environment:
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
    volumes:
      - ./package.json:/usr/app/package.json
      - ./package-lock.json:/usr/app/package-lock.json
      - ./src/index.ts:/usr/app/src/index.ts
      - ./src/server.ts:/usr/app/src/server.ts
    ports:
     - "4000:4000"
    command: sh -c "apt-get install chromium-browser && npm install && npm run prod"