version: "3.9"
services:
  webpage_word_counter:
    image: node:lts-alpine
    working_dir: /usr/app
    volumes:
      - ./package.json:/usr/app/package.json
      - ./package-lock.json:/usr/app/package-lock.json
      - ./tsconfig.json:/usr/app/tsconfig.json
      - ./src/index.ts:/usr/app/src/index.ts
      - ./src/server.ts:/usr/app/src/server.ts
    ports:
     - "4000:4000"
    command: sh -c "npm install && npm run prod"