version: "3"
services:
  node-express-docker:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/app
    expose:
      - "4000"
    ports:
      - "4000:4000"
    command: npm run prod