version: "3"
services:
  node-express-docker:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/app
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: npm run prod